### ISSUE TITLE
Word2Vec vs Character Level Tokenization

### ISSUE THREAD

**Issue by Ahmed-Nezar** [Seif-Yasser-Ahmed/Linux-Code-Generator#2]
Tried the Word2vec tokenization with training but didn't yield any good results it was even worse than the character level tokenization as it will be better with Natural Language instead of Code Generation

**Comment by Seif-Yasser-Ahmed** [comment]
Thanks for testing Word2Vec and sharing the results. It’s good to know that character-level tokenization is currently performing better for this task. As you mentioned, Word2Vec and similar embeddings might be more suited for natural language tasks where semantic meaning is crucial. For code generation, the granularity and flexibility of character-level tokenization seem to be more effective, especially when dealing with variable names and syntax. If you have any other ideas or approaches you’d like to explore, I’m open to experimenting further!
